# Generated by Django 4.1.5 on 2023-01-27 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('rating', models.FloatField(default=5)),
                ('image', models.ImageField(upload_to='product/images/')),
                ('price', models.FloatField(default=0)),
                ('seller', models.CharField(max_length=255)),
                ('brand', models.CharField(max_length=120)),
                ('stock', models.IntegerField(default=0)),
                ('is_cod', models.BooleanField(default=True)),
                ('is_express', models.BooleanField(default=True)),
                ('is_fragile', models.BooleanField(default=False)),
                ('cod_charges', models.FloatField(default=0)),
                ('express_charges', models.FloatField(default=0)),
                ('category', models.CharField(max_length=50)),
                ('sub_category', models.CharField(max_length=50)),
                ('min_qty_to_buy', models.IntegerField(default=1)),
                ('max_qty_to_buy', models.IntegerField(default=1)),
                ('standard_charges', models.IntegerField(default=50)),
                ('description', models.TextField(blank=True, null=True)),
                ('specification', models.TextField(blank=True, null=True)),
                ('is_popular', models.BooleanField(default=False)),
                ('launch_date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ('-launch_date',),
            },
        ),
    ]
